### PR TITLE
Push more info from README to pages.

### PR DESCRIPTION
**Pull request by kk5dire**
# Description/Content changed.
- Moved more info form the master readme to the pages readme 
- Added some needed clarifications to difi when transfering readme over.

### CODE REVIEW

**Comment by kk5dire** [comment]
Should at some point perhaps transfer over from default pages as while easy to setup default pages can be lacking in freedom of style.

**Comment by kk5dire** [comment]
OOP

**Comment by kk5dire** [comment]
I would have wanted to do reviews but shit, I wanted to enable automerge not merge now

**Comment by benfoster04** [comment]
Will review in due course.

**Comment by kk5dire** [comment]
> Will review in due course.

TY ben, make a PR and request my review if you want to change anything

**Pull request merged**
