### PR TITLE
[Formatting] Remove blank spaces

### PR DESCRIPTION
**Pull request by kk5dire**
Remove blank spaces for formatting reasons

### CODE REVIEW

**Review by Tech-TTGames — APPROVED** [review]
Alright but next time use the actual PR template you hear?

**Comment by kk5dire** [comment]
> Alright but next time use the actual PR template you hear?

There would be no applicable or reasonable use to apply the PR template on a change like mine.

How would my *formatting correction* be used in the future?
How would it detract from what this currently is? 
Etc. Etc. 

The PR template makes some sense for a larger addition that is making more changes, but for smaller changes, it is almost completly invalidated.

**Comment by Tech-TTGames** [comment]
> > Alright but next time use the actual PR template you hear?
> 
> There would be no applicable or reasonable use to apply the PR template on a change like mine.
> 
> How would my _formatting correction_ be used in the future? How would it detract from what this currently is? Etc. Etc.
> 
> The PR template makes some sense for a larger addition that is making more changes, but for smaller changes, it is almost completly invalidated.

I don't mean you keep the whole template. Just the general format and remove anything that doesn't work. It's just more uniform that way.

**Comment by kk5dire** [comment]
> > > Alright but next time use the actual PR template you hear?
> > 
> > 
> > There would be no applicable or reasonable use to apply the PR template on a change like mine.
> > How would my _formatting correction_ be used in the future? How would it detract from what this currently is? Etc. Etc.
> > The PR template makes some sense for a larger addition that is making more changes, but for smaller changes, it is almost completly invalidated.
> 
> I don't mean you keep the whole template. Just the general format and remove anything that doesn't work. It's just more uniform that way.

The only thing I would have kept in that case would have been the changes made- 

Which I still feel would be a bit exessive to have 

### Changes made 

- Removed a space

or something along those lines. 

Perhaps I could have done something along the line of

### Changes made
- Removed a space
  - Improved formatting

To make it less empty.

**Comment by kk5dire** [comment]
> Yeah, I don't actually have any issues with it, just for next time.
The problem with having a template is that sometimes there is a situation where the template dosent really apply, and a compromise for the template needs to be made.

Ex, For when there isnt that many things changed, there is less of a need for bulleting or listing items. 
But then again, I will see (*looking into it*)

**Pull request merged**
