### PR TITLE
Taaaaaaags?

### LINKED ISSUE #50: [Feature]: Silent Tags
### Summary

A tag without the direct reply to the command invoker. 

### Feature Description

A tag that trusted support members could use to provide information to the end user without particularly revealing themselves as the command invoker. 

### Justification

This would be useful for informative messages that can be used by moderators and trusted support team members to provide information to other users, to either inform users about something, or to help stop the spread of misinformation in tickets. 

***TLDR***
- Would be useful for information
- Would be useful to stop misinformation
- A command for trusted support/moderators

### Additional Context

I feel this would be a great help with moderation as it acts as a way to help stop the spread of misinformation, provide information, etc. Without specifically calling attention to a moderator or trusted support member. Would be like the anon reply `/respond` command but would contain canned content like the `/tag` command featured in the base bot. 

***Drawbacks***
- Would need DB storage 
- Perhaps would be too ambitious to expect anytime soon

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### LINKED ISSUE #63: [Enhancement]: Ignore specific names of channels
Basically, if the channel starts with X do not apply pinging or stuff. Probably could be just 'ticket types'.

And no, there will not be a whitelist. It's easier to apply defaults to all and then correct some.

### PR DESCRIPTION
**Pull request by Tech-TTGames**
## Description

YABWT

## Motivation and Context

* YABWT - Yet Another Bot With Tags
## Changes Made

- Taaags?
- Anonymous tag sending?
- Embed tags?
- Mention with tag?

## Issues Resolved
- Resolves #50 
- Resolved #63 

## Checklist

- [X] My code follows the style guidelines of this project.
- [X] I have reviewed my own code and ensured it passes all linting tests.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have made corresponding changes to the documentation.

### CODE REVIEW

**Comment by Tech-TTGames** [comment]
Need to add migration and testing.

**Comment by kk5dire** [comment]
On bf8848294a208a47654c344ff588152cbad316c4 did you just have had it wish pylint didn't you

**Comment by benfoster04** [comment]
@Tech-TTGames Is this PR dead?

**Comment by Tech-TTGames** [comment]
@benfoster04 I mean it's merged.

**Pull request merged**
