### PR TITLE
The Update Update

### PR DESCRIPTION
**Pull request by Tech-TTGames**
A general batch of QOL updates.
-  The /join command #23 
- Separated staff roles into perms ("staff") and pings ("observers")
- Shared Config object across cogs. (Less reloads needed)
- _Probably_ less reload-needy owner check
- The Parameters described

### CODE REVIEW

**Review by kk5dire — DISMISSED** [review]
LGTM

**Comment by kk5dire** [comment]
Autofix from @deepsourcebot on https://deepsource.io/gh/Tech-TTGames/Tickets-Plus/run/08e978f9-aa79-486f-b076-02a33dc522df/python/

**Comment by kk5dire** [comment]
Longest check imaginable

**Review by benfoster04 — COMMENTED** [review]
We'll want to probably look further into consistency across the board regarding changes made in extchecks.py and "A probably bad way to work around the poor design of discord.py's app_command checks." Otherwise LGTM great work as always @Tech-TTGames

**Pull request merged**
